apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator
spec:
  selector:
    matchLabels:
      app: moderator
  template:
    metadata:
      labels:
        app: moderator
    spec:
      containers:
      - name: moderator
        image: dazzler/moderator:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4003

---
apiVersion: v1
kind: Service
metadata:
  name: moderator
spec:
  selector:
    app: moderator
  ports:
  - name: moderator
    port: 4003
    targetPort: 4003