apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
spec:
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
      - name: comments
        image: dazzler/comments:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: comments
spec:
  selector:
    app: comments
  ports:
  - name: comments
    port: 4001
    targetPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: comments-node
spec:
  type: NodePort
  selector:
    app: comments
  ports:
  - name: comments
    port: 4001
    targetPort: 4001

