apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: dazzler/posts:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  ports:
  - name: posts
    port: 4000
    targetPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: posts-node
spec:
  type: NodePort
  selector:
    app: posts
  ports:
  - name: posts
    port: 4000
    targetPort: 4000


