apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
spec:
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
      - name: query-service
        image: dazzler/query-service:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4002

---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  selector:
    app: query-service
  ports:
  - name: query-service
    port: 4002
    targetPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: query-service-node
spec:
  type: NodePort
  selector:
    app: query-service
  ports:
  - name: query-service
    port: 4002
    targetPort: 4002





